### PR TITLE
[MODULES-4157] Basic setup with stub methods and placeholder tests

### PR DESCRIPTION
**Pull request by wilson208**
Implements rubocop config and travis config to run rubocop and spec tests.

### CODE REVIEW

**Comment by wilson208** [comment]
The stubbed methods which exist in this PR relate to MODULES-4151 & MODULES-4152.

**Comment by tphoney** [comment]
might be worth squashing the commits. 
install module on ? does that copy the src over ? or download from forge / git
install dependencies, what does that mean

**Comment by wilson208** [comment]
@tphoney Have squashed these commits and updated the README to give more info on the functionality intended to be implemented in the 2 stubbed methods. I will expand this when I implement the methods to give more detailed info on the exact functionality and any parameters.

**Comment by tphoney** [comment]
another cool thing would be to install package dependencies, via yum apt-get or whatever.

**Comment by tphoney** [comment]
also i dont have permission to merge :)

**Comment by wilson208** [comment]
Now added the modules team to have full permissions over this repo. Also, the plan is to implement installing of package dependencies, however I am out most of this sprint so thought this subset of functionality is a start. I did some research of a number of the spec_helper_acceptance.rb files and have identified more functionality for the coming sprint.

**Pull request merged**
